apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: k8s-rails
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: k8s-rails
    spec:
      containers:
        - image: CHANGE-HERE
          imagePullPolicy: Always
          name: app-rails
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
              name: passenger
          env:
            - name: "DATABASE_URL"
              valueFrom:
                secretKeyRef:
                  name: rails
                  key: database
            - name: "SECRET_KEY_BASE"
              valueFrom:
                secretKeyRef:
                  name: rails
                  key: keybase
          command: ["passenger", "start", "-p", "4000", "-e", "production", "--max-pool-size", "2", "--min-instances", "2"]
