apiVersion: v1
kind: Secret
metadata:
  name: rails
type: Opaque
data:
  database: cG9zdGdyZXM6Ly9wb3N0Z3JlczpIb3lESHd1R0lvc000SVBQQDEwNC4xOTYuNTQuNTk6NTQzMi9yYWlsc19wcm9k
  keybase: MGNmYzIyZjhiOTA0MzQwZjViMGQzNjViY2YwM2U2ODQxNzA3MzliNWY4ZGE0MTE0ZGUzOTEyODE4Zjg3NzIzYjE3OWZjOGQ0Njk3NDYzZTQ3YzE5YmVmY2QxMmNmODBhNzkyZWZhZDQyZTIxMTRlYjAzMWRmZmQ3OGIzYjI4MDY=
